<?php
namespace App\Services;
use App\Models\{AuditLog,Expense,ExpenseCategory,ExpenseProof};
use Illuminate\Support\Facades\{DB,Storage,Validator};
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class ExpenseService {
 public function create(array $data,?int $userId,?Expense $replaces=null):Expense{Validator::make($data,['proofs.*.file'=>['file','mimes:jpg,jpeg,png,pdf','max:'.app(SettingService::class)->integer('expense_proof_max_kb')]])->validate();$stored=[];try{return DB::transaction(function()use($data,$userId,$replaces,&$stored){if($replaces){$replaces=Expense::lockForUpdate()->findOrFail($replaces->id);if($replaces->status!=='CANCELLED')$this->fail('expense','Pengeluaran asal harus sudah dibatalkan.');if($replaces->replacement()->exists())$this->fail('expense','Pengeluaran ini sudah memiliki pengeluaran pengganti.');}$category=ExpenseCategory::lockForUpdate()->findOrFail($data['expense_category_id']);if(!$category->active)$this->fail('expense_category_id','Kategori pengeluaran tidak aktif dan tidak dapat digunakan.');if((int)$data['amount']<=0)$this->fail('amount','Nominal pengeluaran harus lebih besar dari nol.');$proofs=$data['proofs']??[];if(!$proofs)$this->fail('proofs','Bukti pengeluaran wajib diunggah.');$expense=Expense::create(['transaction_number'=>$this->number(),'expense_category_id'=>$category->id,'title'=>$data['title'],'description'=>$data['description']??null,'amount'=>$data['amount'],'spent_at'=>$data['spent_at'],'status'=>'POSTED','created_by'=>$userId,'replaces_expense_id'=>$replaces?->id]);foreach($proofs as $row){$file=$row['file'];$path=$file->store('expense-proofs','local');$stored[]=$path;ExpenseProof::create(['expense_id'=>$expense->id,'storage_path'=>$path,'original_name'=>$file->getClientOriginalName(),'mime_type'=>$file->getMimeType(),'size_bytes'=>$file->getSize(),'uploaded_by'=>$userId,'metadata'=>$row['metadata']??null]);}$this->audit('expense.created',$expense,[],['amount'=>$expense->amount,'proof_count'=>count($proofs)],$userId);return $this->detail($expense);});}catch(\Throwable $e){foreach($stored as $path)Storage::disk('local')->delete($path);throw $e;}}
 public function cancel(Expense $expense,string $reason,?int $userId):Expense{return DB::transaction(function()use($expense,$reason,$userId){$expense=Expense::lockForUpdate()->findOrFail($expense->id);if($expense->status==='CANCELLED')$this->fail('expense','Pengeluaran sudah dibatalkan sebelumnya.');$old=$expense->toArray();$expense->update(['status'=>'CANCELLED','cancel_reason'=>$reason,'cancelled_by'=>$userId,'cancelled_at'=>now()]);$this->audit('expense.cancelled',$expense,$old,$expense->fresh()->toArray(),$userId);return $this->detail($expense->fresh());});}
 public function prefill(Expense $expense):array{if($expense->status!=='CANCELLED')$this->fail('expense','Pengeluaran asal harus sudah dibatalkan.');return ['expense_category_id'=>$expense->expense_category_id,'title'=>$expense->title,'description'=>$expense->description,'amount'=>$expense->amount,'spent_at'=>now()->toDateString(),'replaces_expense_id'=>$expense->id];}
 public function detail(Expense $expense):Expense{$expense->load(['category','proofs','creator','canceller','replacement','replacedExpense']);$expense->proofs->each->makeHidden('storage_path');return $expense;}
 public function deleteCategory(ExpenseCategory $category):void{if($category->expenses()->exists())$this->fail('category','Kategori yang sudah digunakan tidak dapat dihapus.');$category->delete();}
 private function number():string{return 'EXP-'.now()->format('Ymd').'-'.strtoupper(substr((string)Str::ulid(),-8));}
 private function fail(string $field,string $message):never{throw ValidationException::withMessages([$field=>$message]);}
 private function audit(string $action,Expense $expense,array $old,array $new,?int $userId):void{AuditLog::create(['user_id'=>$userId,'action'=>$action,'auditable_type'=>Expense::class,'auditable_id'=>$expense->id,'old_values'=>$old,'new_values'=>$new,'ip'=>request()->ip()]);}
}
